// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3wAz59_jkv1jHUSVIwOcng9V2YDkwPW4',
    appId: '1:280404827865:web:0e99e714ac95db035c28c8',
    messagingSenderId: '280404827865',
    projectId: 'monapp-eacdf',
    authDomain: 'monapp-eacdf.firebaseapp.com',
    storageBucket: 'monapp-eacdf.appspot.com',
    measurementId: 'G-G9087MGKTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGocIdoDwrGDDglFdM9gr2LHKc4yPqhGw',
    appId: '1:280404827865:android:13bc99cdd54b9a7d5c28c8',
    messagingSenderId: '280404827865',
    projectId: 'monapp-eacdf',
    storageBucket: 'monapp-eacdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2smZaTTLyfYZZgqj4WOGxVUcM3CX2bsU',
    appId: '1:280404827865:ios:e0af0285be20c8c75c28c8',
    messagingSenderId: '280404827865',
    projectId: 'monapp-eacdf',
    storageBucket: 'monapp-eacdf.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2smZaTTLyfYZZgqj4WOGxVUcM3CX2bsU',
    appId: '1:280404827865:ios:e0af0285be20c8c75c28c8',
    messagingSenderId: '280404827865',
    projectId: 'monapp-eacdf',
    storageBucket: 'monapp-eacdf.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3wAz59_jkv1jHUSVIwOcng9V2YDkwPW4',
    appId: '1:280404827865:web:86529de2d63841a65c28c8',
    messagingSenderId: '280404827865',
    projectId: 'monapp-eacdf',
    authDomain: 'monapp-eacdf.firebaseapp.com',
    storageBucket: 'monapp-eacdf.appspot.com',
    measurementId: 'G-T4632H0NRE',
  );
}
